JENKINS-59908: Fix expandAll call so it works with a Run parameter. (#44)
* Revert "JENKINS-59908: Fix expandAll call so it works with a Run parameter.  (#43)"

This reverts commit 8a67d5f8351f03534d5c03287630857dc09a7abe.

* Improve logging when a blanket Throwable is swallowed.

* Fix `expandAll` call so it works with a `Run` parameter.

Previously, due to the blanket catch of a `Throwable` here, the code was masking the fact that `TokenMacro.expandAll` was never invoked, failing like this:

```
Failed to evaluate macro ''
java.lang.ClassCastException: org.jenkinsci.plugins.workflow.job.WorkflowRun cannot be cast to hudson.model.AbstractBuild
```